services:
  z-way-server:
    build:
      context: .
    container_name: z-way-container
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/ttyACM2:/dev/ttyACM2
      - /dev/ttyACM3:/dev/ttyACM3
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    ports:
      - "8083:8083"
    networks:
      my_network:
        ipv4_address: 192.168.50.100  # Custom static IP
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24  # Custom subnet
    

